[tool.poetry]
name = "jetbrains-manager-tool"
version = "0.1.0"
description = "This tool allows for the streamlined installation, update and removal of various Jetbrains applications."
authors = ["Diogo Caveiro"]
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
